version: '3.8'

services:
  # Reverse Proxy (Main entry point)
  nginx-proxy:
    image: nginx:alpine
    container_name: fuel_reverse_proxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx-proxy.conf:/etc/nginx/nginx.conf:ro
    networks:
      - fuel-network
    depends_on:
      - fuel-dashboard

  # Dashboard Service
  fuel-dashboard:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: fuel_cost_dashboard
    restart: unless-stopped
    expose:
      - "80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./index.html:/usr/share/nginx/html/index.html:ro
    networks:
      - fuel-network

  # API Service (Connect to your existing API)
  # Note: Your existing API should be running separately
  # The reverse proxy will route fuelcost.blackshadow.software to your existing API

volumes:
  fuel_data:

networks:
  fuel-network:
    driver: bridge